name: Publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt -r requirements-dev.txt

      - name: Build the package
        run: |
          python -m build --sdist --wheel

      - name: Publish to Test PyPI
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          TWINE_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }} 
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }} 
        run: |
          twine upload --repository testpypi dist/*

      - name: Publish to PyPI
        if: ${{ github.ref == 'refs/tags/*' }}
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }} 
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }} 
        run: |
          twine upload dist/*
